server:
  port: 9000
  servlet:
    context-path: /inestia-web
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      max-active: 100
      min-idle: 1
      stat-view-servlet:
        allow: true
      test-on-borrow: true
    hikari:
      minimum-idle: 20
      maximum-pool-size: 500
      max-lifetime: 300000
      connection-test-query: SELECT 1
    password: 1234@qwer
#    url: jdbc:mysql://120.236.247.203:37005/qinzhi_db?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    url: jdbc:mysql://192.168.16.252:3306/qinzhi_db?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8&&useSSL=false
    username: root
  thymeleaf:
    cache: false