INSERT INTO `sys_user` (`id`,`organization_id`,`username`,`password`,`salt`,`role_ids`,`group_ids`,`locked`) VALUES (1,1,'admin','844ef3adb0f6a90d0e6d28db80edbe77','be379cd8a830fc5cc04e77c96d544928','1','1',0);
INSERT INTO `sys_role` (`id`,`role`,`description`,`resource_ids`,`available`) VALUES (1,'admin','超级管理员','11,21,31,41,46,69,70,75,80',0);


INSERT INTO `sys_organization` (`id`,`name`,`parent_id`,`parent_ids`,`available`,`priority`,`leaf`) VALUES (1,'琴智科技',0,'0/',1,0,0);
INSERT INTO `sys_organization` (`id`,`name`,`parent_id`,`parent_ids`,`available`,`priority`,`leaf`) VALUES (2,'综合部',1,'0/1/',1,1,0);

INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (1,'资源','MENU','#',0,'0/','',1,'',0,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (11,'组织机构管理','MENU','#',1,'0/1/','organization:*',1,'fa fa-sitemap',3,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (12,'组织机构新增','BUTTON','',11,'0/1/11/','organization:create',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (13,'组织机构修改','BUTTON','',11,'0/1/11/','organization:update',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (14,'组织机构删除','BUTTON','',11,'0/1/11/','organization:delete',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (15,'组织机构查看','BUTTON','',11,'0/1/11/','organization:view',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (21,'用户管理','MENU','#',1,'0/1/','',1,'fa fa-user',1,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (22,'用户新增','BUTTON','',46,'0/1/21/','user:create',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (23,'用户修改','BUTTON','',46,'0/1/21/','user:update',1,'',NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (24,'用户删除','BUTTON','',46,'0/1/21/','user:delete',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (25,'用户查看','BUTTON','',46,'0/1/21/','user:view',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (31,'资源管理','MENU','#',1,'0/1/','resource:*',1,'fa fa-desktop',2,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (32,'资源新增','BUTTON','',31,'0/1/31/','resource:create',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (33,'资源修改','BUTTON','',31,'0/1/31/','resource:update',1,'',NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (34,'资源删除','BUTTON','',31,'0/1/31/','resource:delete',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (35,'资源查看','BUTTON','',31,'0/1/31/','resource:view',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (41,'角色管理','MENU','#role',21,'0/1/','role:*',1,'fa fa-child',2,1);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (42,'角色新增','BUTTON','',41,'0/1/41/','role:create',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (43,'角色修改','BUTTON','',41,'0/1/41/','role:update',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (44,'角色删除','BUTTON','',41,'0/1/41/','role:delete',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (45,'角色查看','BUTTON','',41,'0/1/41/','role:view',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (46,'系统用户','MENU','#user',21,'0/1/11/','user:*',1,'fa fa-wrench',1,1);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (47,'组织机构','MENU','#organization',11,'0/1/11/','organization:*',1,'fa fa-suitcase',NULL,1);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (50,'资源管理','MENU','#resource',31,'0/1/','resource:*',1,'fa fa-cubes',NULL,1);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (69,'系统管理','MENU','#',1,'0/1/','',1,'fa fa-wrench',4,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (70,'发新闻','MENU','#news',69,'0/1/69/','news:*',1,'fa fa-history',NULL,1);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (71,'新闻新增','BUTTON','',70,'0/1/70/','news:create',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (72,'新闻修改','BUTTON','',70,'0/1/70/','news:update',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (73,'新闻删除','BUTTON','',70,'0/1/70/','news:delete',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (74,'新闻查看','BUTTON','',70,'0/1/70/','news:view',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (75,'发招聘','MENU','#job',69,'0/1/69/','job:*',1,'fa fa-history',NULL,1);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (76,'招聘新增','BUTTON','',75,'0/1/75/','job:create',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (77,'招聘修改','BUTTON','',75,'0/1/75/','job:update',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (78,'招聘删除','BUTTON','',75,'0/1/75/','job:delete',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (79,'招聘查看','BUTTON','',75,'0/1/75/','job:view',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (80,'发历程','MENU','#process',69,'0/1/69/','process:*',1,'fa fa-history',NULL,1);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (81,'历程新增','BUTTON','',80,'0/1/80/','process:create',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (82,'历程修改','BUTTON','',80,'0/1/80/','process:update',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (83,'历程删除','BUTTON','',80,'0/1/80/','process:delete',1,NULL,NULL,0);
INSERT INTO `sys_resource` (`id`,`name`,`type`,`url`,`parent_id`,`parent_ids`,`permission`,`available`,`icon`,`priority`,`leaf`) VALUES (84,'历程查看','BUTTON','',80,'0/1/80/','process:view',1,NULL,NULL,0);

INSERT INTO `sys_product`(`id`, `root_name`, `parent_name`, `node_name`, `url`, `dr`) VALUES (11, '人工智能超算产品', '推理计算型', NULL, NULL, 0);
INSERT INTO `sys_product`(`id`, `root_name`, `parent_name`, `node_name`, `url`, `dr`) VALUES (12, '人工智能超算产品', '训练计算型', NULL, NULL, 0);
INSERT INTO `sys_product`(`id`, `root_name`, `parent_name`, `node_name`, `url`, `dr`) VALUES (13, '人工智能超算产品', 'CPU通用计算型', NULL, NULL, 0);
INSERT INTO `sys_product`(`id`, `root_name`, `parent_name`, `node_name`, `url`, `dr`) VALUES (21, '智能加速卡', '思元100', NULL, NULL, 0);
INSERT INTO `sys_product`(`id`, `root_name`, `parent_name`, `node_name`, `url`, `dr`) VALUES (22, '智能加速卡', '思元270', NULL, NULL, 0);
INSERT INTO `sys_product`(`id`, `root_name`, `parent_name`, `node_name`, `url`, `dr`) VALUES (31, '智慧城市', '城市实时仿真', NULL, NULL, 0);
INSERT INTO `sys_product`(`id`, `root_name`, `parent_name`, `node_name`, `url`, `dr`) VALUES (32, '智慧城市', '智能交通系统', NULL, NULL, 0);
INSERT INTO `sys_product`(`id`, `root_name`, `parent_name`, `node_name`, `url`, `dr`) VALUES (33, '智慧城市', '智能安防', NULL, NULL, 0);
INSERT INTO `sys_product`(`id`, `root_name`, `parent_name`, `node_name`, `url`, `dr`) VALUES (34, '智慧产业', '智能教育', NULL, NULL, 0);
INSERT INTO `sys_product`(`id`, `root_name`, `parent_name`, `node_name`, `url`, `dr`) VALUES (35, '智慧产业', '智能医疗', NULL, NULL, 0);
INSERT INTO `sys_product`(`id`, `root_name`, `parent_name`, `node_name`, `url`, `dr`) VALUES (36, '智慧产业', '智能制造', NULL, NULL, 0);
INSERT INTO `sys_product`(`id`, `root_name`, `parent_name`, `node_name`, `url`, `dr`) VALUES (37, '智慧产业', '智能金融', NULL, NULL, 0);
INSERT INTO `sys_product`(`id`, `root_name`, `parent_name`, `node_name`, `url`, `dr`) VALUES (38, '智慧产业', '智能港航', NULL, NULL, 0);
INSERT INTO `sys_product`(`id`, `root_name`, `parent_name`, `node_name`, `url`, `dr`) VALUES (39, '智慧产业', '智能物流', NULL, NULL, 0);
INSERT INTO `sys_product`(`id`, `root_name`, `parent_name`, `node_name`, `url`, `dr`) VALUES (40, '智慧产业', '智能消费', NULL, NULL, 0);
INSERT INTO `sys_product`(`id`, `root_name`, `parent_name`, `node_name`, `url`, `dr`) VALUES (41, '智慧产业', '智能生活娱乐', NULL, NULL, 0);
INSERT INTO `sys_product`(`id`, `root_name`, `parent_name`, `node_name`, `url`, `dr`) VALUES (50, '疫情防控', '疫情防控', NULL, NULL, 0);
INSERT INTO `sys_product`(`id`, `root_name`, `parent_name`, `node_name`, `url`, `dr`) VALUES (51, '创新创业', '创新创业', NULL, NULL, 0);
